server:
  name: "ohw"
  port: 4209
  release_mode: true

auth:
  refresh_token: ""

system_id: ""

network_metrics:
  poll_rate_seconds: 1

db:
  name: "ohw"
  username: "postgres"
  password: "password"
  host: "localhost"
  port: 5432
