{
 "title": "OnHub Web",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Network Up/Down",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(network_metrics_rx{job=\"ohw-service\"}[1m]))",
     "legendFormat": "Download"
    },
    {
     "expr": "sum(rate(network_metrics_tx{job=\"ohw-service\"}[1m]))",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Goroutines count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"ohw-service\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"ohw-service\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{job=\"ohw-service\"}[30s])",
     "legendFormat": "heap size"
    }
   ]
  },
  {
   "title": "Per Device Network Up/Down",
   "type": "graph",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(station_network_metrics_rx{job=\"ohw-service\"}[1m])) by (friendly_name)",
     "legendFormat": "Download - {{friendly_name}}"
    },
    {
     "expr": "sum(rate(station_network_metrics_tx{job=\"ohw-service\"}[1m])) by (friendly_name)",
     "legendFormat": "Upload - {{friendly_name}}"
    }
   ]
  },
  {
   "title": "Network Metrics Polling Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(network_metrics_poll_duration{job=\"ohw-service\"}[1m])) ",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Connected Stations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "connected_stations{quantile=\"1\"}"
    }
   ]
  },
  {
   "title": "Incoming HTTP Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_duration_seconds{job=\"ohw-service\"}[1m])) by (instance, path, method, status)",
     "legendFormat": "{{method}} - {{status}} - {{path}} "
    }
   ]
  }
 ]
}