{
 "title": "OnHub Web",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Incoming HTTP Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_duration_seconds{job=\"ohw-service\"}[1m])) by (instance, path, method)",
     "legendFormat": "{{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"ohw-service\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"ohw-service\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{job=\"ohw-service\"}[30s])",
     "legendFormat": "heap size"
    }
   ]
  }
 ]
}